#!/bin/bash
#
# Skript mis arvutab esimese 10ne paarisarvu summa


summa=0
for (( arv=1; arv<11; arv++ ))
do 
	jaak=$(($arv % 2))
	if [ $jaak -eq 0 ]; then
			summa=$(($summa + $arv))
	fi
done
echo "10ne esimese paarisarvu summa on : $summa"
