#!/bin/bash
#
# Skript mis väljastab Kersti Kaljulaidi valimis aasta

aasta=2016

president="Kersti Kaljulaid"

lause_keskosa=". aastal valiti Eesti presidendiks "

lause="$aasta$lause_keskosa$president"

echo $lause




