#!/bin/bash	
#	
# Skript mis laseb sisestada oma vanust ja annab sulle vanuse staatuse sõltuvalt sinu vanusest.



vanus=0

echo "Sisesta oma vanus: "

read vanus


if  test $vanus -gt 0 -a $vanus -lt 11
  then
	echo "Sa oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
  then 
	echo "Sa oled nooruk"
elif test $vanus -ge 18 -a  $vanus -lt 63
  then 
	echo "Sa oled täiskasvanu"
elif test $vanus -ge 63 
  then
	echo "Sa oled senioor"
else 
	echo "Tekkis tõrge"
fi
